global:
  models:
    qwen-3-5-122b:
      id: RedHatAI/Qwen3.5-122B-A10B-NVFP4
      enabled: true
      resources:
        limits:
          cpu: "32"
          memory: 200Gi
        requests:
          cpu: "24"
          memory: 150Gi
      args:
        - --chat-template
        - /chat-templates/tool_chat_template_qwen.jinja
        - --max-model-len
        - "131072"
        - --enforce-eager
        - --reasoning-parser
        - qwen3
        - --tool-call-parser
        - qwen3_coder
        - --enable-auto-tool-choice
    gpt-oss-120b:
      id: openai/gpt-oss-120b
      enabled: true
      resources:
        limits:
          cpu: "32"
          memory: 200Gi
        requests:
          cpu: "24"
          memory: 150Gi
      args:
        - --tool-call-parser
        - openai
        - --enable-auto-tool-choice

llm-service:
  device: gpu
  deviceConfigs:
    gpu:
      image: vllm/vllm-openai:nightly

clusterGroup:
  namespaces:
    openshift-nfd:
    nvidia-gpu-operator:

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      source: certified-operators

  applications:
    nfd:
      name: nfd
      namespace: openshift-nfd
      path: charts/nfd
    nvidia-config:
      name: nvidia-config
      namespace: nvidia-gpu-operator
      path: charts/nvidia-config
