global:
  models:
    deepseek-r1:
      id: Valdemardi/DeepSeek-R1-Distill-Llama-70B-AWQ
      enabled: true
      resources:
        limits:
          cpu: "32"
          memory: 200Gi
        requests:
          cpu: "24"
          memory: 150Gi
      args:
        - --reasoning-parser
        - deepseek_r1
        - --tool-call-parser
        - llama3_json
        - --enable-auto-tool-choice
        - --quantization
        - awq_marlin
        - --dtype
        - float16
        - --max-model-len
        - "65536"
    gpt-oss-120b:
      id: openai/gpt-oss-120b
      enabled: true
      resources:
        limits:
          cpu: "32"
          memory: 200Gi
        requests:
          cpu: "24"
          memory: 150Gi
      args:
        - --tool-call-parser
        - openai
        - --enable-auto-tool-choice

llm-service:
  device: gpu
  # deviceConfigs:
  #   gpu:
  #     image: vllm/vllm-openai:nightly

clusterGroup:
  namespaces:
    openshift-nfd:
    nvidia-gpu-operator:

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      source: certified-operators

  applications:
    nfd:
      name: nfd
      namespace: openshift-nfd
      path: charts/nfd
    nvidia-config:
      name: nvidia-config
      namespace: nvidia-gpu-operator
      path: charts/nvidia-config
