global:
  pattern: ai-quickstart-rag
  device: cpu # one of 'cpu' (no GPU) or 'gpu' (NVIDIA GPU)
  models:
    llama-3-8b-instruct:
      id: meta-llama/Meta-Llama-3-8B-Instruct
      enabled: true
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*

