apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
    dashboard:
      managementState: Managed
    llamastackoperator:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
